[package]
name = "avr-tester"
version = "0.1.0"
edition = "2021"
authors = ["Patryk Wychowaniec <pwychowaniec@pm.me>"]
license = "MIT"
description = "Functional testing framework for AVR binaries"
readme = "../README.md"
repository = "https://github.com/Patryk27/avr-tester"
keywords = ["avr", "test", "framework", "microcontroller", "simavr"]

[dependencies]
simavr-ffi = "0.1"

[dev-dependencies]
rand = "0.8"
test-case = "2.1"
