[package]
name = "avr-tester"
version = "0.2.2"
edition = "2021"
authors = ["Patryk Wychowaniec <pwychowaniec@pm.me>"]
license = "MIT"
description = "Functional testing framework for AVR firmware"
readme = "../README.md"
repository = "https://github.com/Patryk27/avr-tester"
keywords = ["avr", "test", "framework", "microcontroller", "simavr"]

[dependencies]
avr-simulator = { path = "../avr-simulator", version = "0.2.2" }

[dev-dependencies]
rand = "0.8"
