[workspace]
members = [
    "components-shift-register",
    "components-spi",
    "pins-analog",
    "pins-digital",
    "spi",
    "timeout",
    "uart",
    "xx-bits",
    "xx-eval",
]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
panic = "abort"
