[package]
name = "tests-spi"
version = "0.1.0"
edition = "2021"

[dependencies]
atmega-hal = { git = "https://github.com/Rahix/avr-hal", features = ["atmega328p", "rt"] }
avr-hal-generic = { git = "https://github.com/Rahix/avr-hal" }
embedded-hal = "0.2.3"
panic-halt = "0.2.0"
